compatibility_date = "2022-10-15"
kv_namespaces = [
  {binding = "TIMELINE_KV", id = "3d0353e7e0d64e6fb6a001dfcd54cc7b", preview_id = "3d0353e7e0d64e6fb6a001dfcd54cc7b"},
  {binding = "FEED_KV", id = "fbb8dd3f1c91435b9598f7ed782a2a36", preview_id = "fbb8dd3f1c91435b9598f7ed782a2a36"},
]
name = "peeper-timeline"
workers_dev = false

[durable_objects]
bindings = [{name = "TIMELINE_DO", class_name = "PeeperTimeline"}]

[[migrations]]
new_classes = ["PeeperTimeline"]
tag = "v1"

[build.upload]
format = "modules"
