compatibility_date = "2022-10-15"
name = "orator-crowd"
workers_dev = false

[durable_objects]
bindings = [{name = "CROWD_DO", class_name = "OratorCrowd"}]

[[migrations]]
new_classes = ["OratorCrowd"]
tag = "v1"

[build.upload]
format = "modules"

kv_namespaces = [
  {binding = "FEED_KV", id = "fbb8dd3f1c91435b9598f7ed782a2a36", preview_id = "fbb8dd3f1c91435b9598f7ed782a2a36"},
]
