compatibility_date = "2022-10-15"
name = "peeper-settings"
workers_dev = false

[durable_objects]
bindings = [{name = "SETTINGS_DO", class_name = "PeeperSettings"}]

[[migrations]]
new_classes = ["PeeperSettings"]
tag = "v1"

[build.upload]
format = "modules"
