compatibility_date = "2022-10-15"
kv_namespaces = [
  {binding = "FEED_KV", id = "fbb8dd3f1c91435b9598f7ed782a2a36", preview_id = "fbb8dd3f1c91435b9598f7ed782a2a36"},
  {binding = "CROWD_KV", id = "1fd1e643b2f34c75b74a081ee6146fd3", preview_id = "1fd1e643b2f34c75b74a081ee6146fd3"},
]
name = "peeper-crowd"
workers_dev = false

[durable_objects]
bindings = [{name = "CROWD_DO", class_name = "PeeperCrowd"}]

[[migrations]]
new_classes = ["PeeperCrowd"]
tag = "v1"

[build.upload]
format = "modules"
